
from typing import Any, Optional
class Article:
draft: ArticleState
    internal_description: str
    source: str
    title: str
    title_translations: Any
    summary: str
    summary_translations: Any
    content: str
    content_translations: Any
    call_to_action: str
    call_to_action_translations: Any
    call_to_action_url: str
    date: datetime
    image: str
    image_blob: bytes
    video: str
    video_blob: bytes
    video_type: str
    twitter_bot_redirect: bool
    email_gif: str
    last_modified: datetime
    links: List
    blog: bool
    urls: List
    email_subjects: Any
    push_ios: Any
    push_android: Any
    in_app_label: Any
    in_app_image: str
    in_app_image_blob: bytes
    event_history: Any
    notification_email: bool
    notification_push: bool
    notification_in_app: bool
    notification_priority: int
    notification_weekday: int
    notification_local_hour: int
    notification_local_hour_min: int
    notification_local_hour_max: int
    notification_min_gap: int
    notification_signup_min: int
    notification_signup_max: int
    notification_last_online_min: int
    notification_last_online_max: int
    notification_required_tags: Any
    notification_excluded_tags: Any
    notification_signup_date_min: date
    notification_signup_date_max: date
    notification_transaction_url: str
    VARIATION_SET_NAMES: set
    def add_notification_event(self, event: str) -> None: ...
    def all(self): ...
    def delete(self, **kwargs): ...
    def delete_language(self, language: str) -> bool: ...
    def dynamic_properties(self): ...
    def entity_type(self): ...
    def fields(self): ...
    def from_entity(self): ...
    def get(self) -> Optional: ...
    def get_all_notifications(self) -> List: ...
    def get_best_engagement_percent(self) -> str: ...
    def get_by_id(self, parent = ..., **kwargs): ...
    def get_by_key_name(self, parent = ..., **kwargs): ...
    def get_call_to_action(self, language: str = ...) -> str: ...
    def get_content(self, language: str = ...) -> str: ...
    def get_email_image(self) -> str: ...
    def get_email_subjects(self, language: str) -> Dict: ...
    def get_event_count_7d(self, variation_set_name: str, event: str) -> int: ...
    def get_event_count_total(self, variation_set_name: str, event: str) -> int: ...
    def get_id(self) -> Optional: ...
    def get_in_app_labels(self, language: str, fallback: bool = ...) -> Dict: ...
    def get_language_variations(self, language: Optional = ..., fallback: bool = ...) -> Dict: ...
    def get_link(self, utm_source: Optional = ..., utm_medium: Optional = ..., utm_campaign: Optional = ...) -> str: ...
    def get_notification_local_hour(self) -> int: ...
    def get_notification_local_hour_max(self) -> int: ...
    def get_notification_local_hour_min(self) -> int: ...
    def get_or_insert(self, **kwds): ...
    def get_persistent_url(self) -> str: ...
    def get_push_android(self, language: str) -> Dict: ...
    def get_push_ios(self, language: str) -> Dict: ...
    def get_summary(self, language: str = ...) -> str: ...
    def get_title(self, language: str = ...) -> str: ...
    def get_variation_from_id(self, variation_id: str) -> Tuple: ...
    def get_variation_id(self, variation_set_name: str, variation: str, profile_key: str = ...) -> str: ...
    def gql(self, *args, **kwds): ...
    def has_key(self): ...
    def instance_properties(self): ...
    def is_saved(self): ...
    def is_transactional_notification(self) -> bool: ...
    def key(self): ...
    def kind(self): ...
    def normalize_url(self) -> str: ...
    def parent(self): ...
    def parent_key(self): ...
    def properties(self): ...
    def put(self, **kwargs): ...
    def save(self, **kwargs): ...
    def store(self) -> None: ...
    def store_notification_events(self) -> None: ...
    def to_xml(self, _entity_class = ...): ...
