
from typing import Any, Optional
class StoreConfig:
def all(self): ...
    author: StringProperty
    client_key: StringProperty
    def cloneVariation(self, partner_key: str, language_key: str, variation_key: str, new_client_key: Optional = ..., new_partner_key: Optional = ..., new_language_key: Optional = ..., new_variation_key: Optional = ..., new_variation_author: Optional = ...) -> None: ...
    created: DateTimeProperty
    def delete(self, **kwargs): ...
    def dynamic_properties(self): ...
    editor_version: IntegerProperty
    def entity_type(self): ...
    experiment_key: StringProperty
    experiment_value: StringProperty
    def fields(self): ...
    def from_entity(self): ...
    def get(self) -> Optional: ...
    def getAllConfigs(self) -> Dict: ...
    def getAvailableConfigs(self) -> Dict: ...
    def get_by_id(self, parent = ..., **kwargs): ...
    def get_by_key_name(self, parent = ..., **kwargs): ...
    def get_or_insert(self, **kwds): ...
    def gql(self, *args, **kwds): ...
    def has_key(self): ...
    def instance_properties(self): ...
    is_available: BooleanProperty
    def is_saved(self): ...
    def key(self): ...
    def kind(self): ...
    language_key: StringProperty
    def parent(self): ...
    def parent_key(self): ...
    partner_key: StringProperty
    premium: BooleanProperty
    def properties(self): ...
    def put(self, **kwargs): ...
    def remove(self) -> None: ...
    def save(self, **kwargs): ...
    def serialize(self, expose_all: bool = ...) -> Dict: ...
    def store(self) -> None: ...
    store_data: JSONProperty
    def to_dict(self): ...
    def to_xml(self, _entity_class = ...): ...
    variation_key: StringProperty
    visits_min: IntegerProperty
