
from typing import Any, Optional
class Subscription:
def addPlayTime(self, **kwds): ...
    def addPlayTimeByUID(self, request: Dict) -> bool: ...
    def all(self): ...
    award_at_billing_cycle: IntegerProperty
    award_at_date: DateProperty
    award_to: StringProperty
    billing_cycle: IntegerProperty
    check_at: DateTimeProperty
    country: StringProperty
    def delete(self, **kwargs): ...
    def dynamic_properties(self): ...
    def entity_type(self): ...
    experiments: JSONProperty
    def fields(self): ...
    def from_entity(self): ...
    def get(self) -> Optional: ...
    def getRelativeChurnRate(self, include_trials: bool = ..., for_month: Any = ..., min_sample_size: int = ..., country: Optional = ...) -> Dict: ...
    def getTrialConversionForExperiment(self, end_date: Any, experiment: str, batch_size: int = ...) -> Dict: ...
    def get_by_id(self, parent = ..., **kwargs): ...
    def get_by_key_name(self, parent = ..., **kwargs): ...
    def get_or_insert(self, **kwds): ...
    def gql(self, *args, **kwds): ...
    def has_key(self): ...
    has_pending_revenue_share: BooleanProperty
    id: StringProperty
    def instance_properties(self): ...
    def is_saved(self): ...
    def key(self): ...
    def kind(self): ...
    def parent(self): ...
    def parent_key(self): ...
    partner: StringProperty
    platform: StringProperty
    play_time: JSONProperty
    products: TextProperty
    def properties(self): ...
    purchase_id: StringProperty
    def put(self, **kwargs): ...
    receipt: TextProperty
    referrer: StringProperty
    referrer_ts: DateProperty
    revenue_share_history: JSONProperty
    revenue_share_queue: JSONProperty
    def save(self, **kwargs): ...
    def store(self) -> None: ...
    def to_dict(self): ...
    def to_xml(self, _entity_class = ...): ...
    trial_length: IntegerProperty
    uid: StringProperty
