from datetime import datetime, date, time
from typing import Any, Generic, Iterator, TypeVar, overload, Callable, Type

_T = TypeVar("_T")
_M = TypeVar("_M", bound="Model")

class Key:
    def name(self) -> str: ...
    def id(self) -> int | None: ...
    def kind(self) -> str: ...
    def parent(self) -> "Key | None": ...
    @classmethod
    def from_path(cls, *args: Any, **kwargs: Any) -> "Key": ...

class Property(Generic[_T]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Any = None) -> _T: ...
    def __set__(self, obj: Any, value: _T) -> None: ...

class Model:
    def __init__(self, **kwargs: Any) -> None: ...
    def key(self) -> Key: ...
    def put(self) -> Key: ...
    def delete(self) -> None: ...
    @classmethod
    def get(cls: Type[_M], keys: Any) -> "_M | None": ...
    @classmethod
    def get_by_key_name(
        cls: Type[_M], key_name: str | list[str], parent: Any = None
    ) -> "_M | None": ...
    @classmethod
    def get_or_insert(cls: Type[_M], key_name: str, **kwargs: Any) -> _M: ...
    @classmethod
    def all(cls: Type[_M]) -> "Query[_M]": ...
    @classmethod
    def kind(cls) -> str: ...

class Expando(Model): ...

class Query(Generic[_M]):
    def filter(self, property_operator: str, value: Any) -> "Query[_M]": ...
    def order(self, property: str) -> "Query[_M]": ...
    def ancestor(self, ancestor: Key | Model) -> "Query[_M]": ...
    def get(self) -> _M | None: ...
    def fetch(self, limit: int, offset: int = 0) -> list[_M]: ...
    def count(self, limit: int = 1000) -> int: ...
    def __iter__(self) -> Iterator[_M]: ...

class StringProperty(Property[str]):
    def __get__(self, obj: Any, objtype: Any = None) -> str: ...

class TextProperty(Property[str]):
    def __get__(self, obj: Any, objtype: Any = None) -> str: ...

class IntegerProperty(Property[int]):
    def __get__(self, obj: Any, objtype: Any = None) -> int: ...

class FloatProperty(Property[float]):
    def __get__(self, obj: Any, objtype: Any = None) -> float: ...

class BooleanProperty(Property[bool]):
    def __get__(self, obj: Any, objtype: Any = None) -> bool: ...

class DateTimeProperty(Property[datetime]):
    def __get__(self, obj: Any, objtype: Any = None) -> datetime: ...

class DateProperty(Property[date]):
    def __get__(self, obj: Any, objtype: Any = None) -> date: ...

class TimeProperty(Property[time]):
    def __get__(self, obj: Any, objtype: Any = None) -> time: ...

class BlobProperty(Property[bytes]):
    def __get__(self, obj: Any, objtype: Any = None) -> bytes: ...

class ListProperty(Property[list[_T]], Generic[_T]):
    def __get__(self, obj: Any, objtype: Any = None) -> list[_T]: ...
    def __iter__(self) -> Iterator[_T]: ...

class StringListProperty(ListProperty[str]):
    def __get__(self, obj: Any, objtype: Any = None) -> list[str]: ...
    def __iter__(self) -> Iterator[str]: ...

class ReferenceProperty(Property[Any]):
    def __get__(self, obj: Any, objtype: Any = None) -> Any: ...

class EmailProperty(Property[str]):
    def __get__(self, obj: Any, objtype: Any = None) -> str: ...

class LinkProperty(Property[str]):
    def __get__(self, obj: Any, objtype: Any = None) -> str: ...

def get(keys: Any) -> Model | None: ...
def put(models: Model | list[Model]) -> Key | list[Key]: ...
def delete(models: Any) -> None: ...

class Error(Exception): ...
class BadValueError(Error): ...
class BadKeyError(Error): ...
class NotSavedError(Error): ...
class BadFilterError(Error): ...

from typing import Any, Callable, TypeVar
def transactional(_func = ..., **kwargs) -> Any: ...
