-- Load autocmd feature modules in their original registration order.
require("autocmds.window")
require("autocmds.formatting")
require("autocmds.window_state")
require("themes.engine") -- applies theme colors to plugin UIs (was autocmds/highlights.lua)
require("autocmds.matchpairs")
require("autocmds.winbar")
require("autocmds.integrations")
require("autocmds.buffers")
require("autocmds.macro_recording")
